description: "AI Health Billing Classification"

prompts:
  - "./prompts/classify-account-v1.j2"
  - "./prompts/classify-account-v2.j2"
  - "./prompts/classify-account-v3.j2"

providers:
  - "openai:gpt-4o-mini"
  - "openai:gpt-4o"
  - "openai:gpt-3.5-turbo"
  - "openai:gpt-3.5-turbo-16k"
  - "anthropic:messages:claude-sonnet-4-20250514"
  - "anthropic:messages:claude-3-5-sonnet-20241022"
  - "anthropic:messages:claude-3-5-haiku-20241022"
  - "deepseek:deepseek-chat"

tests:
  - "./test-cases.yaml"

defaultTest:
  options:
    transform: |
      try {
          return JSON.parse(output).classification;
        } catch (e) {
          return output;
        }
  vars:
    classification_list: |
      - awaiting_guarantor
      - payer_pending
      - likely_writeoff
      - needs_manual_review
      - patient_inquiry
      - claim_resubmitted
      - awaiting_payment
      - paid_in_full
      - sent_to_collections
      - provider_pending
      - partial_payment
      - claim_denied
      - under_fraud_review
      - refund_issued
      - itemized_bill_requested
      - payment_plan_active
      - payment_plan_requested
      - claim_appeal_submitted
      - account_closed
      - guarantor_deceased
      - insurance_info_updated
