description: "AI Health Billing Classification"

prompts:
  - "./prompts/classify-account-v1.j2"
  - "./prompts/classify-account-v2.j2"

providers:
  - "openai:gpt-4o-mini"
  - "openai:gpt-4o"
  - "openai:gpt-3.5-turbo"
  - "openai:gpt-3.5-turbo-16k"

testCases:
  - "./test-cases.yaml"
